/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.opensearch.trafficgateway.proxy.java-application-conventions")
}

val opensearchMigrationsVersion: String by rootProject.extra

// This is included to load certs and keys.  Doing it again isn't currently worth it.
val opensearchSecurityPlugin by configurations.creating

dependencies {
    implementation(project(":log4j-plugins"))
    implementation("org.opensearch.migrations.trafficcapture:trafficCaptureProxyServer:$opensearchMigrationsVersion")
    implementation("org.opensearch.migrations.trafficcapture:coreUtilities:$opensearchMigrationsVersion")
    implementation("org.opensearch.migrations.trafficcapture:nettyWireLogging:$opensearchMigrationsVersion")
    implementation("org.opensearch.migrations.trafficcapture:captureOffloader:$opensearchMigrationsVersion")

    implementation("org.apache.commons:commons-lang3")

    implementation("com.fasterxml.jackson.core:jackson-databind")
    
    // TODO: This dependency is deprecated.
    implementation("io.burt:jmespath-jackson")

    implementation("io.netty:netty-all")

    implementation("org.opensearch:opensearch:2.19.4")

    opensearchSecurityPlugin("org.opensearch.plugin:opensearch-security:2.11.1.0")
    implementation(files(zipTree("${opensearchSecurityPlugin.singleFile}").matching {
        include("*.jar")
        exclude("slf*.jar")
    }))

    implementation("com.beust:jcommander:1.82")

    testImplementation(testFixtures("org.opensearch.migrations.trafficcapture:testUtilities:$opensearchMigrationsVersion"))
}

application {
    // Define the main class for the application.
    mainClass.set("org.opensearch.trafficgateway.proxy.ProxyServer")
}